#-----------------------------------------------------------
# Github 

name: My-GitHubActions-Basics 
env:   # переменные окружения создаем 
  APPLICATION_NAME     : "MyFlask"
  DEPLOY_PACKAGE_NAME  : "flask-deploy-ver-${{ github.sha }}"   # чтобы присваивала на каждый commit 09a5b0d
   
on:         # on [push]   по сути мы здесь указываем условие что должно запуститься при определенном событии
   push:
     branches:
         - master   # когда кто-то пушит код в мастер  
# между on и [push]  # нажми control + space выскачать подсказки 
jobs:
  my_testing: # одна наш джоба 
  
     runs-on: ubuntu-latest   # по сути gfit hub action запускает контенер на ubuntu и использует 
     
     # steps это таски как в ansible tasks 
     steps:
     - name: Print Hello Message in Testing
       run:  echo "Hello World from Testing job"   # по сути просто команда linux 
     - name: Execure few commands
     # ниже пример вызова переменных окружений env 
       run : |
         echo "Hello Message1"
         echo "Hello Message2"
         echo "Application name: ${{ env.APPLICATION_NAME }}"

     - name: Git clone my repo 
       uses: actions/checkout@v1    # один из первых степов клаинирует весь репозиторий   
     - name: List corrent folder 
       run : ls -la   # просто список смотрим   

  my_deploy:
      runs-on: ubuntu-latest   # если несколько тогда в скобках 
      needs: [my_testing]  # по сути просто указываю что my_deploy джоба выполняется только после my_testing 
      env:
        VAR1 : "This is Job Level Varaible1" # это переменные которые только внутри конкретной джобы есть 
        VAR2 : "This is Job Level Varaible2"   
      steps:
      - name: Print Hello Message in Deploy
        run:  echo "Hello World from Deploy job"
      
      #выше мы создали внутренние переменные здесь мы их вызываем  выводим на экран грубо говоря 
      - name: Print env vars 
        run : |
           echo "Var1 = ${{ env.VAR1 }}"  
           echo "Var2 = ${{ env.VAR1 }}"
           echo "Var3 = $LOCAL_VAR"
        env: 
          LOCAL_VAR: "This is Super Local Environment variable"
          
           
        # ниже пример использования второй глобальной переменной выше 
      - name: Printing Deployment package    
        run: echo "Deploy pakcage name is ${{ env.DEPLOY_PACKAGE_NAME }}" 
        
      - name: Lets test some packages if they are here 1 
        run: aws --version  # запустим данную команду  
      
      - name: Lets test some packages if they are here 2 
        run: zip  #проверим наличие zip  
 
